.PHONY: clean All

All:
	@echo "----------Building project:[ CHDIGER - Debug ]----------"
	@cd "CHDIGER" && "$(MAKE)" -f  "CHDIGER.mk"
clean:
	@echo "----------Cleaning project:[ CHDIGER - Debug ]----------"
	@cd "CHDIGER" && "$(MAKE)" -f  "CHDIGER.mk" clean
